'use client';

import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';

interface ChatTitleProps {
  /** The chat title to display */
  title: string;
  /** Whether to show the title */
  show: boolean;
  /** Whether the title has been generated by AI */
  isAIGenerated?: boolean;
}

/**
 * ChatTitle displays the chat title with a typewriter animation
 * when the title is received from GPT-4
 */
export const ChatTitle: React.FC<ChatTitleProps> = ({
  title,
  show,
  isAIGenerated = false,
}) => {
  const [displayedTitle, setDisplayedTitle] = useState('');
  const [isAnimating, setIsAnimating] = useState(false);

  useEffect(() => {
    // Only animate if it's an AI-generated title and the title changed
    if (isAIGenerated && title && title !== displayedTitle && !isAnimating) {
      setIsAnimating(true);
      setDisplayedTitle('');
      
      let currentIndex = 0;
      const interval = setInterval(() => {
        if (currentIndex < title.length) {
          setDisplayedTitle(title.slice(0, currentIndex + 1));
          currentIndex++;
        } else {
          clearInterval(interval);
          setIsAnimating(false);
        }
      }, 35); // Same speed as sidebar title animation

      return () => clearInterval(interval);
    } else if (!isAIGenerated || !isAnimating) {
      // If not AI-generated or not animating, show title immediately
      setDisplayedTitle(title);
    }
  }, [title, isAIGenerated, displayedTitle, isAnimating]);

  if (!show || !title) {
    return null;
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: -10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="mb-6 border-b border-gray-200 dark:border-gray-700 pb-4"
    >
      <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
        {displayedTitle}
        {isAnimating && (
          <motion.span
            animate={{ opacity: [0, 1, 0] }}
            transition={{ duration: 0.8, repeat: Infinity }}
            className="inline-block w-0.5 h-5 bg-blue-500 ml-1"
          />
        )}
      </h2>
    </motion.div>
  );
}; 